language: julia

julia:
  - 0.7
  - nightly

os:
  - linux
  - osx

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.build(); Pkg.test(; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("DataFrames")); Pkg.add("Documenter"); Pkg.add("Query"); Pkg.add("CSV"); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; cd(Pkg.dir("DataFrames")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
